name: lista_supermarket
description: Um app de listas de supermercado offline com Hive.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  timeago: ^3.6.1
  pdf: ^3.10.8
  printing: ^5.11.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10+1 # <-- ADICIONE ESTA LINHA
  file_picker: ^8.0.0+1 # <-- ADICIONE ESTA LINHA

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff" # Cor de fundo do ícone adaptativo
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    # --- ATUALIZE ESTA SECÇÃO ---
    - assets/icon/icon.png
    - assets/icon/icon.svg 

