name: lista_supermarket
description: Um app de listas de supermercado offline com Hive.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  
  # Gestão de estado e preferências
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Utilitários de UI e formatação
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  timeago: ^3.6.1

  # Funcionalidade Premium: PDF
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

# Secção específica do Flutter
flutter:
  uses-material-design: true
  
  # A secção de assets deve ter esta indentação exata.
  # Fomos mais explícitos e declarámos o ficheiro diretamente.
  assets:
    - assets/icon/icon.png